version: "3.8"

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticket-robot-sqlserver
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TicketRobot@2025
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - ticket-robot-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TicketRobot@2025 -Q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Redis for message queues and caching
  redis:
    image: redis:7-alpine
    container_name: ticket-robot-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ticket-robot-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass TicketRobot@2025
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "TicketRobot@2025", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Azurite - Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: ticket-robot-azurite
    hostname: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite_data:/data
    networks:
      - ticket-robot-network
    restart: unless-stopped
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/devstoreaccount1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Backend NestJS Application

volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local
  azurite_data:
    driver: local

networks:
  ticket-robot-network:
    driver: bridge
